#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pycscope==1.2.1','console_scripts','pycscope'
__requires__ = 'pycscope==1.2.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pycscope==1.2.1', 'console_scripts', 'pycscope')()
    )
